# Add -DDEBUG to have the program write debugging to serial
#CPPFLAGS = -DDEBUG -DDEBUGVIN -DNO_LOAD_CONTROL
ARDUINO_LIBS = EEPROM Adafruit_NeoPixel
BOARD_TAG = nano328
#BOARD_TAG = uno

include ../arduino_inc.mk

